# Generated by Django 5.2.4 on 2025-07-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTracking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('seen_count', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'match_tracking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_from', models.CharField(max_length=20)),
                ('message_to', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('direction', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=100)),
                ('town', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('ethnicity', models.CharField(max_length=100)),
                ('self_description', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
