# Use official Python base image
FROM python:3.11

# Set working directory
WORKDIR /app

# Install MySQL client dependencies + netcat
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    gcc \
    libmariadb-dev \
    netcat \
    && apt-get clean

# Copy requirement files
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Copy full app
COPY . /app/

# Copy wait-for-it.sh and make it executable
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# Wait for MySQL and then run Django
CMD ["/wait-for-it.sh", "host.docker.internal:3306", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
